"""add trip driver and lifecycle fields

Revision ID: b9a096f9cb79
Revises: 38685aadc18a
Create Date: 2026-09-23 19:06:28.505377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9a096f9cb79'
down_revision = '38685aadc18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['driver_id'], ['id'])
        batch_op.drop_column('started_at')
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
